networks:
  organisation_api:
    external: true
    name: serviceplatformen_organisation_api_app
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  phpfpm:
    image: itkdev/php8.3-fpm:alpine
    networks:
      - organisation_api
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=1024M
      - PHP_POST_MAX_SIZE=305M
      - PHP_UPLOAD_MAX_FILESIZE=300M
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
      - PHP_PM_TYPE=static
      - PHP_PM_MAX_CHILDREN=30
      - PHP_MAX_INPUT_VARS=5000

  memcached:
    environment:
      - MEMCACHED_CACHE_SIZE=128

  clamav:
    image: clamav/clamav:1.5
    restart: unless-stopped
    networks:
      - app
    environment:
      CLAMD_CONF_MaxFileSize: "325M"
      CLAMD_CONF_StreamMaxLength: "325M"
      CLAMD_CONF_MaxScanSize: "400M"

  nginx:
    environment:
      - NGINX_MAX_BODY_SIZE=305M
    labels:
      # mTLS is needed for callbacks from Fordelingskomponenten
      #
      # We can only enable mTLS on (sub)domains; not on a path (contrary to what
      # is claimed on
      # https://community.traefik.io/t/configure-clientauth-mtls-for-docker-container/26935)
      #
      # Note: Using two subdomains, e.g. mtls.selvbetjening.aarhuskommune.dk
      # will not work with Aarhus kommunes wildcard certificate. Therefore we
      # prefix the existing subdomain with `mtls-`.
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:?}-mtls.rule=Host(`mtls-${COMPOSE_SERVER_DOMAIN:?}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:?}-mtls.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:?}-mtls.tls.options=mtls@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:?}-mtls.middlewares=mtls-passtlsclientcert@file"
