# https://github.com/Soluto/oidc-server-mock

# networks:
#   organisation_api:
#     external: true
#     name: serviceplatformen_organisation_api_app

include:
  - docker-compose.oidc.yml

services:
  phpfpm:
    image: itkdev/php8.3-fpm:latest
    networks:
      # frontend is necessary for booking to work locally.
      # @see web/modules/custom/itkdev_booking/README.md
      - frontend
      # - organisation_api
    environment:
      - PHP_MEMORY_LIMIT=512M

  node:
    image: node:16
    profiles:
      - dev
    networks:
      - app
    volumes:
      - .:/app:delegated
    working_dir: /app

  clamav:
    image: clamav/clamav:1.5
    platform: linux/amd64
    networks:
      - app
    ports:
      - "3310"
      - "7357"
    environment:
      CLAMD_CONF_MaxFileSize: "325M"
      CLAMD_CONF_StreamMaxLength: "325M"
      CLAMD_CONF_MaxScanSize: "400M"
