services:
  idp-admin:
    image: ghcr.io/geigerzaehler/oidc-provider-mock:latest
    container_name: idp-admin.${COMPOSE_DOMAIN:?}
    networks:
      - app
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:?}-idp-admin.rule=Host(`idp-admin.${COMPOSE_DOMAIN:?}`)"
    expose:
      - "80"
    command: [
        "--port",
        "80",

        # https://oidc-provider-mock.readthedocs.io/stable/usage.html#predefined-users
        # User matching config/sync/openid_connect.settings.yml
        "--user-claims",
        '{"sub": "administrator", "email": "administrator@example.com", "name": "Administrator", "groups": ["Superadministrator"]}',

        "--user-claims",
        '{"sub": "site_admin", "email": "site_admin@example.com", "name": "Site Admin", "groups": ["SiteAdmin"]}',

        "--user-claims",
        '{"sub": "editor", "email": "editor@example.com", "name": "Tryksen", "groups": ["Redaktoer"]}',

        "--user-claims",
        '{"sub": "flow_designer", "email": "forloeb_designer@example.com", "name": "Flowdesigner", "groups": ["GG-Rolle-Digitaleworkflows-flowdesigner"]}',

        "--user-claims",
        '{"sub": "forloeb_designer", "email": "forloeb_designer@example.com", "name": "Forløbsdesigner", "groups": ["GG-Rolle-Digitaleworkflows-forloebsdesigner"]}',

        "--user-claims",
        '{"sub": "medarbejder", "email": "medarbejder@example.com", "name": "Medarbejder", "groups": ["GG-Rolle-Digitaleworkflows-medarbejder"]}',
      ]

  # https://github.com/geigerzaehler/oidc-provider-mock
  idp-citizen:
    image: ghcr.io/geigerzaehler/oidc-provider-mock:latest
    container_name: idp-citizen.${COMPOSE_DOMAIN:?}
    networks:
      - app
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME:?}-idp-citizen.rule=Host(`idp-citizen.${COMPOSE_DOMAIN:?}`)"
    expose:
      - "80"
    command: [
        "--port",
        "80",

        # https://oidc-provider-mock.readthedocs.io/stable/usage.html#predefined-users
        "--user-claims-file",
        "/app/user-claims.yaml",
      ]
    volumes:
      - idp-citizen-data:/app
    # https://docs.docker.com/reference/compose-file/services/#depends_on
    depends_on:
      idp-citizen-generate-user-claims:
        condition: service_completed_successfully

  # Generate user data for idp-citizen service
  idp-citizen-generate-user-claims:
    image: mikefarah/yq
    # We must run as root to allow the image to write the user claims into the shared volume (idp-citizen-data).
    user: root
    # @todo Merge in our CVR mock
    entrypoint:
      - sh
      - -c

      # Notice that we fold the block (by using `>-`) to avoid having to add
      # line continuation characters (`\`) in the shell command.
      #
      # Run
      #
      #   docker compose up --force-recreate idp-citizen --detach ; docker compose logs idp-citizen-generate-user-claims
      #
      # to check any changes the incantations below.
      - >-
        yq '. | sort_keys(.) | .[] | sort_keys(.) | select(.persondata.status.status == (1, 3, 5, 7)) | [{
        "sub": key + ": " + .persondata.navn.personadresseringsnavn,
        "status": .persondata.status.status,
        "cpr": key,
        "aud": "client-id"
        }]' /input/citizen-data.yaml > /app/user-claims.yaml
        && cat /app/user-claims.yaml

    volumes:
      - idp-citizen-data:/app
      - ./${OS2WEB_DATALOOKUP_MOCK_PERSON_LOOKUP_PATH:-web/modules/custom/itkdev_example_forms/modules/os2web_datalookup_mock/resources/PersonLookup.yaml}:/input/citizen-data.yaml

volumes:
  idp-citizen-data:
